#!/bin/bash

# Handle any input errors.
if [ -z $1 ]; then # If $1 is null then print error and exit.

	echo "No directory provided. Use 'chd help' to get a usage guide."
	return

elif [ ! -z $2 ]; then # If $2 is not null then...

	if [ $1 != "add" ] && [ $1 != "delete" ]; then # If $1 is not add or delete then print error and exit.

        	echo "$1 is not a valid command. Use 'chd help' to get a usage guide."
        	return

	fi

elif [ ! -z $3 ]; then # If $3 is not null then...
		
	if [ ! -d $3 ]; then # If $3 is not a directory then print error and exit.

		echo "'$3' is not a valid directory on this computer."
		echo "Use 'chd help' to get a usage guide."
		return

	fi

fi

# Get the length of the directory list.
length=$(wc -l < chdlist) 

# Handle valid inputs.
if [ $length == 0 ]; then # If the length of the directory list is 0 then print error and exit.

	echo "No directories set. See 'chd help' on how to add directories."
	return

elif [ $1 == "list" ]; then # If $1 is list then print the supported directories.

	echo "---------------------"
	echo "Supported Directories"
	echo "---------------------"
	echo "projects: $projects"	
	echo "work: $work"
	echo "skopos: $skopos"
	echo "---------------------"

elif [ $1 == "help" ]; then # If $1 is help then print out a usage guide.

	echo "This command is used to shorten 'cd' to certain directories."
	echo "It is used by specifying a directory after chd: 'chd directory'"
	echo "A list of valid directories can be viewed with: 'chd list'"
	echo "Directories can be added with 'chd add name directory':"
	echo "chd add space ~/Documents/space"
	echo "Now 'chd space' will cd to the directory '~/Documents/space'"
	echo "Directories can be deleted with: 'chd delete name'"
	echo "chd delete space"

else # Else...

	found=false

	for val in $(<chdlist) 	
	do
		echo $val
	done 

	if ! $found; then

		echo "$1 is not a supported directory. See directories with 'chd list'."

	fi

fi
