#!/bin/bash

chddir=$(pwd) # Store the installation directory into chddir.

# Add $HOME into chddir
home='$HOME'
prefix="/home/$USER"
chddir=${chddir#"$prefix"}
chddir="$home$chddir"

tab='    ' # For appropriate spacing.

# Add the directory to .profile.
echo '' >> ~/.profile
echo '# Adds chd to path. If uninstalling also remove chd from ~/.bash_aliases.' >> ~/.profile
echo "if [ -d "$chddir" ] ; then" >> ~/.profile

# Create the proper variable to add to path.
pathchd='PATH="'
pathchd+="$chddir" 
pathchd+=':$PATH'
pathchd+='"'
echo "$tab$pathchd" >> ~/.profile

echo 'fi' >> ~/.profile

# Add an alias to .bash_aliases.
echo "alias chd='. chd.sh'" >> ~/.bash_aliases

# Tell the user log out must occur for changes to take effect.
echo 'Changes made to ~/.profile and ~/.bash_aliases.'
echo 'Log Out or Restart needed for installation to complete.'